language: general

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull acidgenomics/basejump
  - docker images

script:
  - docker run -ti --user="bioc" --volume="${PWD}:/transformer" --workdir="/transformer" acidgenomics/basejump Rscript -e 'source("travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
